### PR TITLE
Json sanitizing

### PR DESCRIPTION
**Pull request by themmj**
The sanitization of received and returned JSON is now defined inside the data types instead of being cluttered inside the handlers. @lucaschimweg what do you think about this approach?

### CODE REVIEW

**Comment by lucaschimweg** [comment]
Looks really good.

**Comment by lucaschimweg** [comment]
Only question would be if we want requests setting sanitized fields to fail silently. Should we just ignore these fields or should we provide an error? What do you think?

**Comment by themmj** [comment]
i think we should just ignore them. the only time a request is trying to overwrite a protected field would be when a request is formed outside of our apis. then we should just expect the user to have properly read the documentation. so we might need to update the documentation to reflect that.
the biggest reason for keeping silent is to hide the hidden attributes like `isArchived`. creating an error message will either expose server logic or will not be informative in any way

**Comment by lucaschimweg** [comment]
Okay, sound good! Thanks!

**Review by lucaschimweg — APPROVED** [review]

**Pull request merged**
